import { z } from "zod";

export const CreateSessionInputSchema = z.object({
	userId: z.string().uuid("User ID is required"),
});

export type CreateSessionInput = z.infer<typeof CreateSessionInputSchema>;

export const CreateSessionOutputSchema = z.object({
	sessions: z.array(
		z.object({
			id: z.string().uuid("Session ID is required"),
			userId: z.string().uuid("User ID is required"),
			createdAt: z.date({ message: "Created at is required" }),
			updatedAt: z.date({ message: "Updated at is required" }),
		}),
	),
});

export type CreateSessionOutput = z.infer<typeof CreateSessionOutputSchema>;

/**
 * Player state in a game session
 */
export interface PlayerDto {
	life: number;
	maxLife: number;
	mana: number;
	maxMana: number;
	hand: string[]; // card IDs
	deck: string[]; // card IDs
	board: string[]; // card IDs
}

/**
 * Full game state from the Lua engine
 */
export interface GameStateDto {
	sessionId: string;
	turn: number;
	phase: string;
	players: PlayerDto[];
	currentPlayer?: number;
}

/**
 * Game events for animations/UI feedback
 */
export interface GameEventDto {
	type: string;
	payload?: Record<string, unknown>;
}

/**
 * Session DTO as stored in Redis/DynamoDB and returned by API.
 */
export interface SessionDto {
	/** Session ID (generated by Lua engine on init) */
	id: string;
	/** Full game state from the Lua engine */
	state: GameStateDto;
	/** Events generated in the last action */
	// events: GameEventDto[];
	/** User ID who owns this session */
	userId: string | null;
	/** When the session was created */
	createdAt: string; // ISO string
	/** Last update timestamp */
	updatedAt: string; // ISO string
}

/**
 * Create session response (API output)
 */
export interface CreateSessionResponseDto {
	sessions: SessionDto[];
}
