/**
 * Session DTO as stored in Redis/DynamoDB.
 * Represents a game match/session with its full state.
 */
export interface SessionDto {
	/** Session ID (generated by Lua engine on init) */
	id: string;
	/** Full game state from the Lua engine (matches engine-protocol.ts GameState) */
	state: {
		sessionId?: string;
		turn?: number;
		phase?: string;
		players?: unknown[];
		[key: string]: unknown;
	};
	/** User ID who owns this session */
	userId: string | null;
	/** When the session was created */
	createdAt: string; // ISO string
	/** Last update timestamp */
	updatedAt: string; // ISO string
}
